- name: Install rust crates
  hosts: localhost
  become_user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Install prerequisites
      become: true
      become_user: root
      apt:
        name:
          - cmake

    - name: Install the crates
      community.general.cargo:
        executable: "{{ lookup('env', 'HOME') }}/.cargo/bin/cargo"
        name:
          - starship
          - eza
          - bat
          - ripgrep
          - du-dust
          - fd-find
          - rm-improved
          - zoxide
        locked: true
