- name: Install fonts
  hosts: localhost

  tasks:
    - name: Download Fonts
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip
        dest: /tmp/fonts.zip
        force: "yes"

    - name: Make fonts directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.fonts"
        state: directory
        mode: "0755"

    - name: Unzip fonts
      command:
        chdir: /tmp
        cmd: "unzip fonts.zip -d {{ lookup('env', 'HOME') }}/.fonts"
        creates: "{{ lookup('env', 'HOME') }}/.fonts/JetBrainsMonoNLNerdFont-Regular.ttf"

    - name: Reload font cache
      command: fc-cache -fv
