- name: Install Alacritty
  hosts: localhost

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      become: true
      changed_when: false

  tasks:
    - name: check if Alacritty is installed
      shell: infocmp
      register: alacritty_installed
      ignore_errors: true

    - name: Install Alacritty prerequisites
      become: true
      apt:
        name:
          - cmake
          - pkgconfig
          - libfreetype6-dev
          - libfontconfig1-dev
          - libxcb-xfixes0-dev
          - libxkbcommon-dev
          - python3
          - libegl1-mesa-dev
      when: alacritty_installed is failed

    - name: Clone Alacritty repository
      git:
        repo: https://github.com/alacritty/alacritty
        dest: /tmp/alacritty
        clone: true
        version: "v0.12.3"
      when: alacritty_installed is failed

    - name: Compile Alacritty
      shell:
        chdir: /tmp/alacritty
        cmd: cargo build --release
      when: alacritty_installed is failed

    - name: Add to terminfo
      become: true
      shell:
        chdir: /tmp/alacritty
        cmd: tic -xe alacritty,alacritty-direct extra/alacritty.info

    - name: Copy binary to path
      become: true
      shell:
        chdir: /tmp/alacritty
        cmd: cp target/release/alacritty /usr/local/bin

    - name: Copy logo
      become: true
      shell:
        chdir: /tmp/alacritty
        cmd: cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg

    - name: Install desktop file
      become: true
      shell:
        chdir: /tmp/alacritty
        cmd: desktop-file-install extra/linux/Alacritty.desktop

    - name: Update desktop database
      become: true
      shell:
        chdir: /tmp/alacritty
        cmd: update-desktop-database

    - name: Install alacritty as x-terminal-emulator alternative
      become: true
      shell: update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/bin/alacritty 50

    - name: Set alacritty as the default
      become: true
      shell: update-alternatives --set x-terminal-emulator /usr/bin/alacritty
