- name: Install zsh
  hosts: localhost

  tasks:
    - name: Install zsh
      become: true
      ansible.builtin.apt:
        name: zsh

    - name: Register current user name
      shell: whoami
      register: current_user

    - name: Change default shell to zsh
      become: true
      ansible.builtin.shell: "chsh -s $(which zsh) {{ current_user.stdout }}"
