# In case you don't like git submodules
- name: Install NVIM
  hosts: localhost
  tasks:
    - name: Check if nvim exists
      stat:
        path: /user/local/bin/nvim
      register: nvim

    - name: Clone nvim repository
      git:
        repo: https://github.com/neovim/neovim
        dest: /tmp/neovim
        clone: true
        version: "v0.9.4"
      when: not nvim.stat.exists

    - name: Install nvim build dependencies
      become: true
      apt:
        name:
          - ninja-build
          - gettext
          - libtool
          - libtool-bin
          - autoconf
          - automake
          - cmake
          - g++
          - pkg-config
          - unzip
          - curl
        state: present
      when: not nvim.stat.exists

    - name: Build nvim release version
      community.general.make:
        chdir: /tmp/neovim
        params:
          CMAKE_BUILD_TYPE: Release
      when: not nvim.stat.exists

    - name: Install nvim release version
      become: true
      community.general.make:
        chdir: /tmp/neovim
        target: install
      when: not nvim.stat.exists

    - name: Delete tmp neovim
      file:
        path: /tmp/neovim
        state: absent
      when: not nvim.stat.exists
