- name: Install Rust
  hosts: localhost
  become: true
  become_user: "{{ lookup('env', 'USER') }}"

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      become_user: root
      changed_when: False

  vars:
    user: "{{ ansible_user_id }}"

  tasks:
    - name: check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: true

    - name: Download Rust install script
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: "0755"
        force: "yes"
      when: cargo_exists is failed
      tags:
        - rust

    - name: Install rust/cargo
      shell: /tmp/sh.rustup.rs -y
      when: cargo_exists is failed
      tags:
        - rust

