- name: Install Rust
  hosts: localhost
  become: true
  become_user: "{{ lookup('env', 'USER') }}"

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      become_user: root
      changed_when: False

  vars:
    user: "{{ ansible_user_id }}"

  tasks:
    - name: Download Rust install script
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: "0755"
        force: "yes"
      tags:
        - rust

    - name: Install rust/cargo
      shell:
        cmd: /tmp/sh.rustup.rs -y
        creates: "{{ lookup('env', 'HOME') }}/.cargo/bin/cargo"
      tags:
        - rust
