- name: Use stow to create symlinks
  hosts: localhost

  tasks:
    - name: Install stow
      become: true
      ansible.builtin.apt:
        name: stow

    - name: Run stow
      command:
        cmd: "stow --target {{ lookup('env', 'HOME') }} --verbose=2 dotfiles"
        chdir: '{{ playbook_dir }}/..'
      register: result
      changed_when: 'result.stderr is search("LINK: ")'
