- name: Use stow to create symlinks
  hosts: localhost

  tasks:
    - name: Install stow
      become: true
      ansible.builtin.apt:
        name: stow

    - name: Run stow
      loop:
        - alacritty
        - nvim
        - starship
        - zsh
      command:
        cmd: "stow --target {{ lookup('env', 'HOME') }} --verbose=2 {{ item }}"
        chdir: "{{ playbook_dir }}/../configs"
      register: result
      changed_when: 'result.stderr is search("LINK: ")'
