- name: Install Zathura
  hosts: localhost
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      become_user: root
      changed_when: False

  tasks:
    - name: Download Zathura
      apt:
        name: zathura
